const PASS_HASH="6f12879e3d9e2ba887598d781e61125fdd02aab66f6fb136a86d9221cec47222";
const CK="v2rayPanelConfigs",UK="v2rayPanelUsers",SK="v2rayPanelServers",$=id=>document.getElementById(id);
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function login(){if(await hash($("pw").value)===PASS_HASH){sessionStorage.ok="1";location.href="dashboard.html"}else{$("err").textContent="رمز اشتباه است";$("pw").value="";$("pw").focus()}}
function logout(){sessionStorage.removeItem("ok");location.href="index.html"}
const uid=()=>crypto.randomUUID?crypto.randomUUID():"id-"+Date.now()+"-"+Math.random().toString(36).slice(2);
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),configs=()=>get(CK,[]),users=()=>get(UK,[{id:"default",name:"کاربر اصلی"}]),savedServers=()=>get(SK,[]);
function init(){if(!location.pathname.endsWith("dashboard.html")){if(sessionStorage.ok==="1"&&location.pathname.endsWith("index.html"))location.href="dashboard.html";return}if(sessionStorage.ok!=="1"){location.href="index.html";return}if(!localStorage.getItem(UK))put(UK,users());if($("servers")&&!$("servers").children.length)addServer();renderAll()}
function showView(v){["dashboardView","builderView","serversView","usersView","importView"].forEach(x=>$(x)?.classList.add("hidden"));$(v==="dashboard"?"dashboardView":v==="builder"?"builderView":v==="servers"?"serversView":v==="users"?"usersView":"importView")?.classList.remove("hidden");if(v==="builder"){fillUsers();fillSavedServerSelect()}if(v==="servers")renderSavedServers();if(v==="users")renderUsers();if(v==="dashboard")renderAll();scrollTo({top:0,behavior:"smooth"})}
function startNewConfig(){showView("builder");$("editId").value="";$("builderTitle").textContent="ساخت کانفیگ";$("cfgName").value="";$("userCount").value=1;$("limitGB").value=100;$("durationDays").value=30;$("usedGB").value=0;$("credential").value="";$("transport").value="tcp";$("path").value="/vless";$("host").value="";$("tls").checked=true;$("servers").innerHTML="";addServer();$("shareLink").value="";$("jsonOut").value="";$("qr").innerHTML='<span>QR بعد از ذخیره نمایش داده می‌شود</span>'}
function addServer(d={host:"",port:443}){const w=document.createElement("div");w.className="server-row";w.innerHTML='<input class="server-host" placeholder="IP یا دامنه"><input class="server-port" type="number" min="1" max="65535" value="'+(d.port||443)+'"><button class="danger small">حذف</button>';w.querySelector(".server-host").value=d.host||"";w.querySelector("button").onclick=()=>w.remove();$("servers").appendChild(w)}
function fillUsers(sel){if(!$("cfgUser"))return;let us=users();$("cfgUser").innerHTML=us.map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join("");if(sel)$("cfgUser").value=sel}
function addUser(){let n=prompt("نام کاربر:");if(!n?.trim())return;let count=+(prompt("تعداد کاربر مجاز برای این حساب:",1)||1);let u=users();u.push({id:uid(),name:n.trim(),allowedUsers:Math.max(1,count)});put(UK,u);renderAll();fillUsers();toast("کاربر اضافه شد")}
function editUser(id){let u=users().find(x=>x.id===id);if(!u)return;let n=prompt("نام کاربر:",u.name);if(!n?.trim())return;let count=+(prompt("تعداد کاربر مجاز:",u.allowedUsers||1)||1);u.name=n.trim();u.allowedUsers=Math.max(1,count);put(UK,users().map(x=>x.id===id?u:x));renderAll();fillUsers()}
function delUser(id){if(id==="default"){toast("کاربر اصلی حذف نمی‌شود");return}if(configs().some(c=>c.userId===id)){toast("این کاربر هنوز کانفیگ دارد");return}put(UK,users().filter(x=>x.id!==id));renderAll()}
function renderUsers(){let cs=configs();$("userRows").innerHTML=users().map(u=>`<tr><td>${esc(u.name)}</td><td>${cs.filter(c=>c.userId===u.id).length}</td><td>${u.allowedUsers||1}</td><td><button class="secondary small" onclick="editUser('${u.id}')">ویرایش</button> <button class="danger small" onclick="delUser('${u.id}')">حذف</button></td></tr>`).join("")}
function fillSavedServerSelect(){if(!$("savedServerSelect"))return;let a=savedServers();$("savedServerSelect").innerHTML='<option value="">از IP/Port ذخیره‌شده انتخاب کن...</option>'+a.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.host)}:${x.port}</option>`).join("")}
function addSavedServer(){let id=$("savedServerSelect").value;if(!id)return;let s=savedServers().find(x=>x.id===id);if(s)addServer(s)}
function addSavedServerManual(){let name=prompt("نام سرور:", "Server "+(savedServers().length+1));if(!name)return;let host=prompt("IP یا دامنه:");if(!host)return;let port=+(prompt("Port:",443)||443);let note=prompt("یادداشت (اختیاری):","");let a=savedServers();a.push({id:uid(),name:name.trim(),host:host.trim(),port:port,note:note||""});put(SK,a);renderSavedServers();fillSavedServerSelect();toast("سرور ذخیره شد")}
function editSavedServer(id){let s=savedServers().find(x=>x.id===id);if(!s)return;let name=prompt("نام:",s.name);if(!name)return;let host=prompt("IP یا دامنه:",s.host);if(!host)return;let port=+(prompt("Port:",s.port)||443);let note=prompt("یادداشت:",s.note||"");s={...s,name,host,port,note};put(SK,savedServers().map(x=>x.id===id?s:x));renderSavedServers();fillSavedServerSelect()}
function delSavedServer(id){put(SK,savedServers().filter(x=>x.id!==id));renderSavedServers();fillSavedServerSelect()}
function renderSavedServers(){$("savedServerRows").innerHTML=savedServers().map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.host)}</td><td>${s.port}</td><td>${esc(s.note||"-")}</td><td><button class="secondary small" onclick="editSavedServer('${s.id}')">ویرایش</button> <button class="danger small" onclick="delSavedServer('${s.id}')">حذف</button></td></tr>`).join("")}
function saveConfig(){let id=$("editId").value||uid(),name=$("cfgName").value.trim()||"کانفیگ جدید",protocol=$("protocol").value,servers=[...document.querySelectorAll(".server-row")].map(r=>({host:r.querySelector(".server-host").value.trim(),port:+r.querySelector(".server-port").value||443})).filter(x=>x.host);if(!servers.length){toast("حداقل یک IP یا دامنه وارد کن");return}let days=Math.max(0,+$("durationDays").value||0),old=configs().find(c=>c.id===id),created=old?.createdAt||new Date().toISOString();let c={id,name,protocol,servers,credential:$("credential").value.trim()||old?.credential||uid(),transport:$("transport").value,path:$("path").value.trim()||"/",host:$("host").value.trim(),tls:$("tls").checked,userId:$("cfgUser").value||"default",userCount:Math.max(1,+$("userCount").value||1),limitGB:Math.max(0,+$("limitGB").value||0),usedGB:Math.max(0,+$("usedGB").value||0),createdAt:created,expiresAt:days?new Date(Date.now()+days*864e5).toISOString():null,active:old?.active!==false};let a=configs();put(CK,old?a.map(x=>x.id===id?c:x):[c,...a]);showGenerated(c);renderAll();toast(old?"کانفیگ بروزرسانی شد":"کانفیگ ساخته شد")}
function share(c,s){let q=new URLSearchParams();if(c.transport!=="tcp")q.set("type",c.transport);if(c.tls){q.set("security","tls");if(c.host)q.set("sni",c.host)}if(c.transport==="ws")q.set("path",c.path);if(c.transport==="grpc")q.set("serviceName",c.path);if(c.host&&!c.tls)q.set("host",c.host);let tail=(q.toString()?"?"+q:"")+"#"+encodeURIComponent(c.name);if(c.protocol==="VLESS")return`vless://${encodeURIComponent(c.credential)}@${s.host}:${s.port}${tail}`;if(c.protocol==="Trojan")return`trojan://${encodeURIComponent(c.credential)}@${s.host}:${s.port}${tail}`;if(c.protocol==="Shadowsocks"){let x=btoa(unescape(encodeURIComponent("aes-128-gcm:"+c.credential))).replace(/=+$/,"");return`ss://${x}@${s.host}:${s.port}${tail}`}let j={v:"2",ps:c.name,add:s.host,port:String(s.port),id:c.credential,aid:"0",scy:"auto",net:c.transport,type:"none",host:c.host||"",path:c.path,tls:c.tls?"tls":"",sni:c.host||""};return"vmess://"+btoa(unescape(encodeURIComponent(JSON.stringify(j))))}
function clientJSON(c){let ss={network:c.transport,security:c.tls?"tls":"none"};if(c.transport==="ws")ss.wsSettings={path:c.path,headers:c.host?{Host:c.host}:{}};if(c.transport==="grpc")ss.grpcSettings={serviceName:c.path||"grpc"};let out=c.servers.map(s=>{if(c.protocol==="VLESS")return{protocol:"vless",settings:{vnext:[{address:s.host,port:s.port,users:[{id:c.credential,encryption:"none"}]}]},streamSettings:ss};if(c.protocol==="VMess")return{protocol:"vmess",settings:{vnext:[{address:s.host,port:s.port,users:[{id:c.credential,alterId:0,security:"auto"}]}]},streamSettings:ss};if(c.protocol==="Trojan")return{protocol:"trojan",settings:{servers:[{address:s.host,port:s.port,password:c.credential}]},streamSettings:ss};return{protocol:"shadowsocks",settings:{servers:[{address:s.host,port:s.port,method:"aes-128-gcm",password:c.credential}]}}});return{log:{loglevel:"warning"},inbounds:[{listen:"127.0.0.1",port:10808,protocol:"socks",settings:{udp:true}}],outbounds:out}}
function showGenerated(c){$("shareLink").value=share(c,c.servers[0]);$("jsonOut").value=JSON.stringify(clientJSON(c),null,2);$("qr").innerHTML="";if(window.QRCode)new QRCode($("qr"),{text:$("shareLink").value,width:210,height:210,correctLevel:QRCode.CorrectLevel.M})}
function editConfig(id){let c=configs().find(x=>x.id===id);if(!c)return;showView("builder");$("editId").value=c.id;$("builderTitle").textContent="ویرایش کانفیگ";$("cfgName").value=c.name;$("protocol").value=c.protocol;$("userCount").value=c.userCount||1;$("limitGB").value=c.limitGB||0;$("usedGB").value=c.usedGB||0;$("durationDays").value=c.expiresAt?Math.max(0,Math.ceil((new Date(c.expiresAt)-Date.now())/864e5)):0;$("credential").value=c.credential;$("transport").value=c.transport;$("path").value=c.path;$("host").value=c.host;$("tls").checked=c.tls;fillUsers(c.userId);$("servers").innerHTML="";c.servers.forEach(addServer);showGenerated(c)}
function toggleConfig(id){let a=configs().map(c=>c.id===id?{...c,active:c.active===false?true:false}:c);put(CK,a);renderAll();toast(a.find(c=>c.id===id).active?"کانفیگ فعال شد":"کانفیگ متوقف شد")}
function usage(id){let c=configs().find(x=>x.id===id);let v=prompt("حجم مصرف‌شده (GB):",c.usedGB||0);if(v===null)return;c.usedGB=Math.max(0,+v||0);put(CK,configs().map(x=>x.id===id?c:x));renderAll();toast("مصرف بروزرسانی شد")}
function delConfig(id){if(confirm("این کانفیگ حذف شود؟")){put(CK,configs().filter(c=>c.id!==id));renderAll();toast("حذف شد")}}
function renderAll(){renderStats();renderConfigs();renderUsers();renderSavedServers();fillUsers();fillSavedServerSelect()}
function status(c){if(c.active===false)return"متوقف";if(c.expiresAt&&new Date(c.expiresAt)<new Date())return"منقضی";if(c.limitGB>0&&c.usedGB>=c.limitGB)return"حجم تمام";return"فعال"}
function renderStats(){let a=configs();$("statConfigs").textContent=a.length;$("statActive").textContent=a.filter(x=>status(x)==="فعال").length;$("statUsers").textContent=users().length;$("statUsed").textContent=gb(a.reduce((n,x)=>n+(+x.usedGB||0),0))}
function renderConfigs(){let q=($("search")?.value||"").toLowerCase(),a=configs().filter(c=>!q||[c.name,c.protocol,...c.servers.map(s=>s.host)].join(" ").toLowerCase().includes(q));$("configRows").innerHTML=a.map(c=>{let s=c.servers[0]||{},st=status(c);return`<tr><td><b>${esc(c.name)}</b><small>${esc(users().find(u=>u.id===c.userId)?.name||"کاربر اصلی")}</small></td><td>${c.protocol}</td><td>${esc(s.host||"-")}${c.servers.length>1?` <span class="badge">+${c.servers.length-1}</span>`:""}</td><td>${s.port||"-"}</td><td>${c.userCount||1}</td><td>${gb(c.usedGB)} / ${c.limitGB?gb(c.limitGB):"∞"}</td><td>${date(c.expiresAt)}</td><td><span class="status-pill ${st==="فعال"?"ok":st==="متوقف"?"stop":st==="منقضی"?"bad":"warn"}">${st}</span></td><td class="ops"><button class="small" onclick="editConfig('${c.id}')">ویرایش</button><button class="secondary small" onclick="toggleConfig('${c.id}')">${c.active===false?"فعال‌سازی":"توقف"}</button><button class="secondary small" onclick="usage('${c.id}')">مصرف</button><button class="danger small" onclick="delConfig('${c.id}')">حذف</button></td></tr>`}).join("");$("emptyConfigs").style.display=a.length?"none":"block"}
function openImport(){$("importLink").value="";$("importStatus").textContent="";showView("import")}
function importLink(){try{let c=parseLink($("importLink").value.trim());let days=Math.max(0,+$("importDays").value||0);c.name=$("importName").value.trim()||c.name;c.limitGB=Math.max(0,+$("importLimit").value||0);c.userCount=Math.max(1,+$("importUsers").value||1);c.usedGB=0;c.active=true;c.expiresAt=days?new Date(Date.now()+days*864e5).toISOString():null;put(CK,[c,...configs()]);renderAll();editConfig(c.id);toast("کانفیگ از URL وارد شد")}catch(e){$("importStatus").textContent="لینک معتبر یا پشتیبانی‌شده نیست."}}
function parseLink(raw){let u=new URL(raw),p=u.protocol.slice(0,-1).toLowerCase(),name=decodeURIComponent(u.hash.slice(1)||"کانفیگ واردشده"),q=u.searchParams,transport=q.get("type")||"tcp",tls=q.get("security")==="tls",path=q.get("path")||q.get("serviceName")||"/",host=q.get("sni")||q.get("host")||"",cred,proto;if(p==="vless"){cred=decodeURIComponent(u.username);proto="VLESS"}else if(p==="trojan"){cred=decodeURIComponent(u.username);proto="Trojan"}else if(p==="ss"){cred=decodeURIComponent(escape(atob(u.username))).split(":").slice(1).join(":");proto="Shadowsocks"}else if(p==="vmess"){let j=JSON.parse(decodeURIComponent(escape(atob(raw.split("://")[1]))));cred=j.id;proto="VMess"}else throw 0;if(!cred||!u.hostname)throw 0;return{id:uid(),name,protocol:proto,servers:[{host:u.hostname,port:+u.port||443}],credential:cred,transport,path,host,tls,userId:"default"}}
function copyLink(){navigator.clipboard.writeText($("shareLink").value).then(()=>toast("لینک کپی شد"))}
function downloadLink(){blob($("shareLink").value,"v2ray-link.txt","text/plain")}
function exportData(){blob(JSON.stringify({users:users(),configs:configs(),servers:savedServers()},null,2),"v2ray-panel-backup.json","application/json")}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(Array.isArray(d.users))put(UK,d.users);if(Array.isArray(d.configs))put(CK,d.configs);if(Array.isArray(d.servers))put(SK,d.servers);renderAll();toast("بازیابی شد")}catch{toast("فایل معتبر نیست")}};r.readAsText(f)}
function blob(x,n,t){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([x],{type:t}));a.download=n;a.click()}
function gb(n){return(Math.round((+n||0)*10)/10)+" GB"}function date(v){return v?new Intl.DateTimeFormat("fa-IR",{dateStyle:"short"}).format(new Date(v)):"بدون انقضا"}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function toast(s){let t=$("toast");if(!t)return;t.textContent=s;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2200)}
init();
